server:
  port: 8080

spring:
  application:
    name: kafkaDemo

    # Producer properties
    kafka:
      producer:
        bootstrap-servers: 127:0:0:1:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # Common Kafka Properties
    auto.create.topics.enable: true

  trade:
    topic-name: MESSAGE_TOPIC

  datasource:
    url: jdbc:h2:mem:friendship;DB_CLOSE_DELAY=-1
    username: admin
    password:

  jpa:
    properties:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        show-sql: true


  h2:
    console:
      enable: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true